### ISSUE TITLE
What about tracking the time of buzzer, not time remaining?

### ISSUE THREAD

**Issue by soft-ke** [jfeiber/buzzer#142]
Then customers know when they got in line.

Downside is restaurants might not want that because then customers know exactly how long they have waited.. although this is good if people often think that they have been waiting forever but really it's only been 15 minutes.

**Comment by jfeiber** [comment]
Yea, we agree that for the customer it's definitely beneficial, but I think from the restaurant's perspective (and from the limited number of host/hostesses we've talked to), they don't really want anything related to the wait time being displayed. 

Putting the estimated wait time on the Buzzer seems to be confusing people so I think we're just going to remove any mention of wait time on the Buzzer display altogether. We're going to leave it in the wait list on the web app so it can possibly inform host/hostess of what party they want to buzz next (if a party has been waiting for 40 minutes and you told them 20, you probably want to seat them).

**Comment by jfeiber** [comment]
Closing this and re-opening as an issue in buzzer-embedded: https://github.com/jfeiber/buzzer-embedded/issues/31
