### ISSUE TITLE
Confirmation Dialogues After Actions

### ISSUE THREAD

**Issue by carterjbastian** [jfeiber/buzzer#144]
After adding a party to the list and deleting/seating a party, it would be nice if there was a dialog box that let me know what action I just took. This would be especially helpful if you were to implement archiving or recording with deleted and seated parties (you could link directly to the list of deleted or seated parties)

**Comment by jfeiber** [comment]
We actually currently archive all delete and seated parties, and then that information is displayed in the analytics section. 

Confirmation boxes is a nice idea, but I think for now we're going to leave it as is. I don't think we see a huge benefit to having them and the dialogue boxes would crowd the UI.
