### ISSUE TITLE
What is "Kevin has fun with friends"?

### ISSUE THREAD

**Issue by soft-ke** [jfeiber/buzzer#149]
I don't get what the dropdown menu next to Unlink is. I agree that Kevin can have fun with friends

**Comment by michaelmachlin** [comment]
Good find! It was a fun little Easter egg we threw in while building the Buzzer Management page. It was initially a placeholder for possible other buzzer-related actions, but we realized the unlink functionality was all we needed. I'll take that out.

**Comment by michaelmachlin** [comment]
Fixed with #155.
