### ISSUE TITLE
Changing party size

### ISSUE THREAD

**Issue by soft-ke** [jfeiber/buzzer#150]
This could be a good feature because parts of a party could cancel, or there could be people added, and if a restaurant lets people change party sizes like that then they need to track how many people they need to seat.

**Comment by MJAlperin23** [comment]
backend changes covered by #160 

@michaelmachlin frontend updates needed -- call /frontend_api/update_party_size

send party size in POST named as "new_party_size"

**Comment by michaelmachlin** [comment]
@themacexpert was dying to work on this so I'll let him have it (cc @MJAlperin23)

**Comment by themacexpert** [comment]
see #174
