### ISSUE TITLE
Include folder architecture in readme

### ISSUE THREAD

**Issue by ngolini22** [jfeiber/buzzer#152]
I read through your code and personally can't give you any suggestions because my JS is pretty rusty and your code is extremely well commented so I was never confused reading it which is great. I think one thing you could do a little better job at is documenting the file structure in the Architecture section of your README. It took me a few minutes to find the meat of the code because this is a different framework from which I've done web dev in, so some kind of description as to what files are in each folder and what the important files are. Like I said, your code itself reads very smoothly and is clean.

**Comment by jfeiber** [comment]
Thanks, we'll update the README to include folder architecture for the final milestone.

**Comment by jfeiber** [comment]
https://github.com/jfeiber/buzzer/commit/0b6f48c982c8a3b2cb5916db11c94bcec73e3e94
