### ISSUE TITLE
Scaling up

### ISSUE THREAD

**Issue by ngolini22** [jfeiber/buzzer#153]
One thing I was wondering was how are you going to scale this project up to actually be used by a few restaurant with a few hundred customers a week. Is the website already at the point where it could be used commercially? Are your databases going to be able to handle all that data? Or do you think you may have to switch to a sql server or something? Another thing I was wondering was have you considered making your app compatible with any other devices/as an offline desktop app? I feel like writing this as a software for restaurant computers or as a desktop app could be pretty significant in terms of restaurant-usability. By having this as a web-app the restaurants have to rely on a strong internet connection and would need a backup plan if internet was ever too slow or down. I think overall it could make the app more reliable for restaurants, but then again, I don't have experience in scaling projects up that large. I think that you have a product that a lot of restaurants would get behind, so these are just the things I'd think about on a larger scale. Great product!

**Comment by MJAlperin23** [comment]
These are decent points but our objective for this project was to create a working model of what a system like this could be and thus we were more concerned with spending time building out features and user experience than a robust system that could scale to full enterprise level. That said, while we do believe the system could scale to a certain point, given time and resources we would certainly need to evaluate the system and optimize for heavy usage.

Closing for now.

**Comment by MJAlperin23** [comment]
To address the desktop app portion, we felt that a web-app was the best option as it allows the customer to use a device of their choice and does not require a specific application download and setup to do so. This means the application can be easily accessed from any device with internet connection (computer, ipad, windows tablet etc.) and did not require a separate app to be built for device. While the internet connection is a potential issue, with most restaurants having some sort of wifi or ethernet connection (usually both public and private) as well as the possibility of using a data connected device, we believe that the majority of potential customers would have no issue with this requirement.
