### ISSUE TITLE
Fix Settings Cog in Small Size Screen

### ISSUE THREAD

**Issue by MJAlperin23** [jfeiber/buzzer#156]
When window is smaller header defaults to list, however settings cog looks strange in this list and the logout is in the wrong text color

**Comment by themacexpert** [comment]
Visual of issue: 
<img width="311" alt="screen shot 2017-02-12 at 4 37 24 pm" src="https://cloud.githubusercontent.com/assets/5834262/22866272/901f50f8-f141-11e6-98b9-6c73978ed38f.png">

**Comment by michaelmachlin** [comment]
It's not a bug, it's a feature!
![img_2745](https://cloud.githubusercontent.com/assets/12465207/22866394/e5fb2f04-f143-11e6-856c-9d9ab9169496.png)

**Comment by themacexpert** [comment]
resolved
