### ISSUE TITLE
Refreshing page when waiting for buzzer adds party

### ISSUE THREAD

**Issue by MJAlperin23** [jfeiber/buzzer#65]
if the page is manually refreshed while the dialog is up waiting for a buzzer to be connected the party is added without a buzzer -- happened while testing locally, can't confirm issue on prod

**Comment by jfeiber** [comment]
It's in production. There's a javascript timeout that runs every 30 seconds that updates the waitlist. That runs asynchronously so the waitlist will update even when the wait for a buzzer modal is active. I don't think it's a huge issue for now so I think we can wait until next term to fix

**Comment by jfeiber** [comment]
If you guys can't figure it out then you can re-assign me

**Comment by michaelmachlin** [comment]
All fixed thanks to @jfeiber (#118)
