### ISSUE TITLE
Buzz button is still there for phoneaheads

### ISSUE THREAD

**Issue by jfeiber** [jfeiber/buzzer#66]

**Comment by michaelmachlin** [comment]
![screen shot 2016-11-15 at 4 33 31 pm](https://cloud.githubusercontent.com/assets/12465207/20326195/b8be3eac-ab55-11e6-9783-365cdc9d572d.png)

**Comment by themacexpert** [comment]
Issue resolved:
<img width="436" alt="screen shot 2017-01-15 at 3 46 47 pm" src="https://cloud.githubusercontent.com/assets/5834262/21966036/da349dba-db39-11e6-91e0-ea5b1471a32b.png">
