### ISSUE TITLE
Refactor Some of Frontend Code

### ISSUE THREAD

**Issue by jfeiber** [jfeiber/buzzer#83]
The biggest thing that needs to be refactored is the `buzzer.js` method `repopulateTable`. Right now if you update the table structure in the HTML template you also need to update it in this method. `repopulateTable` should really be changed so that it's table-structure agnostic.

**Comment by jfeiber** [comment]
If you can't figure it out re-assign me

**Comment by michaelmachlin** [comment]
(Ref #90 #95 #102)
