### ISSUE TITLE
Resolve spacing issues with window adjustment

### ISSUE THREAD

**Issue by themacexpert** [jfeiber/buzzer#93]
Buttons are collapsed even when window is sufficiently large.
<img width="948" alt="screen shot 2017-01-11 at 4 23 17 pm" src="https://cloud.githubusercontent.com/assets/5834262/21867873/30b52ca0-d81e-11e6-8710-c435115e66ac.png">

**Comment by themacexpert** [comment]
resolved. to be included in the next pr.

**Comment by jfeiber** [comment]
This got fixed somewhere along the line.
