### ISSUE TITLE
Waitlist Button Configurations

### ISSUE THREAD

**Issue by themacexpert** [jfeiber/buzzer#97]
We need to configure the buttons on the waitlist page to include a 3rd button in each row that says seat party. We would like the button to be green or another color that goes along well with the color scheme. @michaelmachlin  Can you choose this color that fits well? Thanks.

**Comment by michaelmachlin** [comment]
#000000

**Comment by michaelmachlin** [comment]
Resolved with dark green #006400 and 20% darker dark green #003100
